# @author DieFriiks / CustomCraftDev / undeaD_D
# @version 1.0
# @github https://github.com/CustomCraftDev/advanceddeath

debug: false
nopermission-msg: '&CYou shall not pass !!!'

Death:
  Default:
    Respawn: false
    Inventory: 100
    Armor: 100
    Hotbar: 100
    Onlyfrompvp: false
    Command:
      - 'say [Guest]%playername% was killed'
  Member:
    Respawn: false
    Inventory: 100
    Armor: 80
    Hotbar: 100
    Onlyfrompvp: false
    Command:
      - 'say [Member]%playername% was killed by %killer%'
  Admin:
    Respawn: true
    Inventory: 0
    Armor: 1
    Hotbar: 100
    Onlyfrompvp: true
    Command:
      - 'say [Admin]%playername% was killed by %killer%'
Respawn:
  Default:
  Member:
    - '1,60,2'
    - '10,20,1'
  Admin:
    - '1,60,4'
    - '10,50,10'
    
