name: AdvancedDeath
main: advanceddeath.AdvancedDeath
description: Requested Plugin by undeaD_D
version: 1.0
author: DieFriiks
authors: [DieFriiks, CustomCraftDev, undeaD_D]
databse: false
depends: [Vault]
commands:
  ad:
    usage: /ad <reload/disable/reset>
    description: Commands from AdvancedDeath plugin
permissions:
  advanceddeath.*:
    description: AdvancedDeath admin permission
    children:
      advanceddeath.reload: true
      advanceddeath.reset: true
      advanceddeath.disable: true
  advanceddeath.reload:
    description: reload the AdvancedDeath plugin
  advanceddeath.reset:
    description: reset the AdvancedDeath config
  advanceddeath.disable:
    description: disable the AdvancedDeath plugin, till next server reload
